### ISSUE TITLE
Website's design

### ISSUE THREAD

**Issue by datkat21** [pieosteam/pieosteam.github.io#2]
### Website design needs to be fixed; we're working on it.
See you when we're done with the next version of the website!

**Comment by MatteeCodes** [comment]
I don't think we will finish right now.

**Comment by MatteeCodes** [comment]
Old Website will continue to be in use

**Comment by datkat21** [comment]
We updated the website finally!

**Comment by actuallyexeon** [comment]
PieOS is now apart of Limey
