### ISSUE TITLE
Website SSL (encryption) problems

### ISSUE THREAD

**Issue by datkat21** [pieosteam/pieosteam.github.io#3]
#2 We are having some website problems (SSL error) and we will fix it later.
@actuallyexeon By any chance could you help me with this?

I tried using some SSL tester and it says certificate mismatch.
![image](https://user-images.githubusercontent.com/49850194/94335221-a6b53d80-ff9f-11ea-82e7-070e1dd946e0.png)

I did some more tests and it says the grade is T. Is there any way we could fix this issue?
![image](https://user-images.githubusercontent.com/49850194/94335273-0f041f00-ffa0-11ea-91b6-85d0f4577360.png)

**Comment by actuallyexeon** [comment]
peiosteamded
